# -*- coding: utf-8 -*-
"""10_Nested Lists

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qwnEFjgRrVzKj-yofY8-hbb9zHPwfO2z
"""

if __name__ == '__main__':
    students = []
    for _ in range(int(input())):
        name = input()
        score = float(input())
        students.append([name, score])

    unique_grades = sorted(set(score for name, score in students))
    second_lowest_grade = unique_grades[1]
    second_lowest_students = [name for name, score in students if score == second_lowest_grade]
    second_lowest_students.sort()
    for student in second_lowest_students:
        print(student)