# -*- coding: utf-8 -*-
"""2. Python If-Else

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m6SOI4-QiirIJhGRhZ_YNQp3Cr8dWwQG

This Colab Notebook is specified for solutions of Hacker Rank Questions. Let's get started :)
"""

#!/bin/python3

import math
import os
import random
import re
import sys


if __name__ == '__main__':
    n = int(input().strip())
    if n%2 != 0:
        print("Weird")
    elif n%2==0 and n<=5 and n>=2:
        print("Not Weird")
    elif n%2 == 0 and n<=20 and n>=6:
        print("Weird")
    else:
        print("Not Weird")