# -*- coding: utf-8 -*-
"""5. Loops

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m6SOI4-QiirIJhGRhZ_YNQp3Cr8dWwQG

This Colab Notebook is specified for solutions of Hacker Rank Questions. Let's get started :)
"""

if __name__ == '__main__':
    n = int(input())

    for i in range(n):
        print(i*i)