# -*- coding: utf-8 -*-
"""6. Write a function

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m6SOI4-QiirIJhGRhZ_YNQp3Cr8dWwQG

This Colab Notebook is specified for solutions of Hacker Rank Questions. Let's get started :)
"""

def is_leap(year):
    leap = False

    # Write your logic here
    greg_years = [1800, 1900, 2100, 2200, 2300, 2500]
    if year%4==0:
        if year in greg_years:
            leap = False
        else:
            leap = True

    return leap

year = int(input())
print(is_leap(year))