# -*- coding: utf-8 -*-
"""7. Print Function

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m6SOI4-QiirIJhGRhZ_YNQp3Cr8dWwQG

This Colab Notebook is specified for solutions of Hacker Rank Questions. Let's get started :)
"""

if __name__ == '__main__':
    n = int(input())
    # a number n
    # print 1...n
    # write a for loop which iterates from 1 to n
    # a var which keeps on concatenating every next number
    # print the var at the end

    seq = ''
    for i in range(1, n+1):
        seq = seq + str(i)

    print(seq)