# -*- coding: utf-8 -*-
"""8. No Idea!

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m6SOI4-QiirIJhGRhZ_YNQp3Cr8dWwQG

This Colab Notebook is specified for solutions of Hacker Rank Questions. Let's get started :)
"""

# Enter your code here. Read input from STDIN. Print output to STDOUT
# Read integers n and k from the first line
if __name__ == '__main__':
    n, m = map(int, input().split())
    nums = map(int, input().split())
    a = set(map(int, input().split()))
    b = set(map(int, input().split()))

    happiness = 0
    for i in nums:
        if i in a:
            happiness+= 1
        if i in b:
            happiness -= 1
    print(happiness)